  
name: build
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    container: python:3.6-slim

    steps:
    - uses: actions/checkout@v2

    - name: Install pybuilder
      run: pip install pybuilder

    - name: Install dependencies
      run: pyb install_dependencies --no-venvs

    - name: Execute build
      run: pyb -X --no-venvs